version = 1

[*]
jinja = true
# Increase log-verbosity to 5 to see the raw RPC chatter between server and harness
log-verbosity = 4
stop-timeout = 3

flash-attn = on
models-max = 1

; device = Vulkan0
# Setting informed by https://github.com/ggml-org/llama.cpp/pull/7412#issuecomment-2120427347
# TODO: Change to Turboquant once merged into llama.cpp main branch
cache-type-k = q8_0
cache-type-v = q5_0
# q_4_0 is almost half the size and the degradation from q8_0 is not measurable with
# llama-perplexity, but the whole internet says they're terrible?!?
#

; np = 4                  ; Parallel request batching (default: 4)
; cb = on                 ; continuous batching (essential with np>1)
; t = 16                  ; generation threads (1/physical core) 

# My quick optimizations
kv-unified = on
parallel = 1
no-mmap = true
cache-ram = 32768 
batch-size = 8192
ubatch-size = 2048
# cache reuse via KV shifting, Pi sends full conversation history each request. This reuses cached prefix instead of re-evaluating. 
cache-reuse = 512


[Qwen3.6-35B-A3B]
# The best quality model that is performant on less
# than 24 GiB VRAM, as of 2026-06-04

# 17.6 GiB, 98.71% accuracy, 56±5 tok/s
hf = byteshape/Qwen3.6-35B-A3B-MTP-GGUF:Qwen3.6-35B-A3B-IQ4_XS-3.97bpw

# Choose a context size
ctx-size = 65536
; ctx-size = 131072  # 128k recommended on 8 GiB VRAM
; ctx-size = 262144  # 256k recommended on 10 GiB+ VRAM

# Never touch ngl or speed will drop drastically
ngl = 99
# Progressively reduce n-cpu-moe from 40 to 0 until you get memory errors
# (the smaller the ctx-size the more experts you can offload to GPU)
n-cpu-moe = 40

# Suppress Qwen-specific warning
image-min-tokens = 1024  

# Enable MTP
spec-type = draft-mtp
spec-draft-n-max = 3
;spec-type = ngram-mod
;spec-ngram-mod-n-match = 24
;spec-ngram-mod-n-min = 48
;spec-ngram-mod-n-max = 64

# Comment out to move mmproj to VRAM for faster image analysis
no-mmproj-offload = true

# Prevent infinite loops in the inner monologue
# https://whamp.github.io/blog/qwen-3-6-27b-livecodebench-reasoning-budget/
reasoning-budget = 8192
reasoning-budget-message = "My reasoning budget is exhausted, but I have enough information to answer directly now.</think>"

# Choose one set of parameters depending on usage
# From https://huggingface.co/unsloth/Qwen3.6-35B-A3B-MTP-GGUF

# Thinking mode for general tasks
; temperature = 1.0
; top_p = 0.95
; top_k = 20
; min_p = 0.0
; presence_penalty = 1.5
; repeat_penalty = 1.0
; # preserve_thinking makes the context baloon and is
; # harmful when the KV cache is quantized
; chat-template-kwargs = {"preserve_thinking":false}

# Thinking mode for precise coding tasks 
temperature = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0
# preserve_thinking makes the context baloon and is
# harmful when the KV cache is quantized
chat-template-kwargs = {"preserve_thinking":false}

# Instruct (or non-thinking) mode for general tasks
; temperature = 0.7
; top-p = 0.8
; top-k = 20
; min-p = 0.0
; presence-penalty = 1.5
; repeat-penalty = 1.0
; chat-template-kwargs = {"enable_thinking":false}

# Instruct (or non-thinking) mode for reasoning tasks
; temperature = 1.0
; top-p = 0.95
; top-k = 20
; min-p = 0.0
; presence-penalty = 1.5
; repeat-penalty = 1.0
; chat-template-kwargs = {"enable_thinking":false}

[Gemma4-E2B]
# 2.6 GiB, 222±4 tok/s
hf = unsloth/gemma-4-E2B-it-qat-GGUF:UD-Q4_K_XL
ctx-size = 131072
parallel = 2
ngl = 99
temperature = 1.0
top-p = 0.95
top-k = 64
; chat-template-kwargs = {"enable_thinking":false}
# Crashes https://github.com/ggml-org/llama.cpp/issues/24400
;spec-type = draft-mtp
;spec-draft-n-max = 2

[Gemma4-E4B]
# 4.2 GiB, 137±5 tok/s
hf = unsloth/gemma-4-E4B-it-qat-GGUF:UD-Q4_K_XL
ctx-size = 131072
parallel = 2
ngl = 99
temperature = 1.0
top-p = 0.95
top-k = 64
chat-template-kwargs = {"enable_thinking":false}
# Enable MTP
;spec-type = draft-mtp
;spec-draft-n-max = 2
# NTP
;spec-type = ngram-mod
;spec-ngram-mod-n-match = 24
;spec-ngram-mod-n-min = 48
;spec-ngram-mod-n-max = 64
