#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx='startx $XINITRC'

[ -f "$MBSYNCRC" ] && alias mbsync='mbsync -c $MBSYNCRC'

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
  alias $command="sudo $command"
done
unset command

se() {
  choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
  [ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
}

# Verbosity and settings that you pretty much just always are going to want.
alias \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI" \
  bc="bc -ql" \
  rsync="rsync -vrPlu" \
  mkd="mkdir -pv" \
  yt="yt-dlp --embed-metadata -i --default-search 'ytsearch'" \
  yta="yt-dlp --embed-metadata --default-search 'ytsearch' -i -x -f bestaudio/best" \
  ytt="yt-dlp --skip-download --write-thumbnail" \
  yt-whatsapp="yt-dlp --embed-metadata -f 'bestvideo[height<=1080]+bestaudio/best' --recode-video mp4" \
  ffmpeg="ffmpeg -hide_banner" \
  adog='git log --all --decorate --oneline --graph' \
  bat="cat /sys/class/power_supply/BAT?/capacity"

# Colorize commands when possible.
alias \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi" \
  ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
  ka="killall" \
  g="git" \
  trem="transmission-remote" \
  sdn="shutdown -h now" \
  e='$EDITOR' \
  v='$EDITOR' \
  p="pacman" \
  xi="sudo xbps-install" \
  xr="sudo xbps-remove -R" \
  xq="xbps-query -R" \
  xs="xbps-query -Rs" \
  z="zathura" \
  svenv="source venv/bin/activate" \
  cx='chmod +x' \
  myp='ps -fjH -u $USER'

# This enables the `pauseallmpv` command.
#alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Wayland / SwayWM specific settings
alias wf-cutout='$(wf-recorder -g "$(slurp)")'
alias logout="[[ -o login ]] && logout || qdbus org.kde.ksmserver /KSMServer logout 0 0 1"

alias \
  lf="lfub" \
  magit="nvim -c MagitOnly" \
  ref='shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutenvrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc'
