#!/usr/bin/env bash
set -euo pipefail

BW_BIN="$HOME/.local/bin/bw-cli"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=github-release-manager
source "$SCRIPT_DIR/github-release-manager"
gh_release_install bitwarden/clients --pattern "^bw-linux.*\.zip$" --bin bw --name bw-cli

exec "$BW_BIN" "$@"
