# github-release-manager configuration file

[prismlauncher]
repo = "PrismLauncher/PrismLauncher"
pattern = '\.AppImage$'
name = "prismlauncher"
gui = true

[godot]
repo = "godotengine/godot"
pattern = "Godot_v.*_linux"
gui = true

[bw]
repo = "bitwarden/clients"
pattern = '^bw-linux.*\.zip$'
bin = "bw"

[steamless]
repo = "staernid/steamless-rs"

[gamux]
repo = "staernid/gamux"

[ludusavi]
repo = "mtkennerly/ludusavi"
pattern = 'ludusavi\-.*\-linux\.tar\.gz'
gui = true

