# github-release-manager configuration file
#
# [example-app]
# repo = "owner/repo"
# pattern = '.*\\.tar\\.gz$'  # Optional asset regex
# bin = "example"             # Optional binary name inside archive
# gui = true                  # Optional: Create desktop launcher

[prismlauncher]
repo = "PrismLauncher/PrismLauncher"
pattern = '\.AppImage$'
name = "prismlauncher"
gui = true

[godot]
repo = "godotengine/godot"
pattern = 'Godot_v.*_linux'
gui = true

[bw]
repo = "bitwarden/clients"
pattern = '^bw-linux.*\.zip$'
bin = "bw"

[steamless]
repo = "staernid/steamless-rs"

[gamux]
repo = "staernid/gamux"
