font_family        Noto
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

adjust_line_height 3
cursor white
cursor_blink_interval      0
scrollback_lines 5000
wheel_scroll_multiplier 5
url_color #0087BD
url_style curly
open_url_with chromium
enable_audio_bell no
window_alert_on_bell yes
bell_on_tab yes

enabled_layouts Tall:bias=65, Fat:bias=65, Stack, Grid, Horizontal, Vertical

window_border_width 1

window_margin_width 4

window_padding_width 6

active_border_color #666666  

inactive_border_color #333333  

inactive_text_alpha .93

tab_bar_margin_width 4

tab_bar_style fade

tab_fade 1 1 1

active_tab_foreground   #282828
active_tab_background   #bbbbbb
active_tab_font_style   bold
inactive_tab_foreground #eeeeee
inactive_tab_background #282828
inactive_tab_font_style normal

color0 #000000
color8 #4a4a4a

#: black

color1 #d41723
color9 #f4273a

#: red

color2 #69d03c
color10  #99f04c

#: green

color3  #dfc22b
color11 #fff20b

#: yellow

color4  #434eff
color12 #037eff

#: blue

color5  #d359d7
color13 #f389f7

#: magenta

color6  #43cef4
color14 #33def4

#: cyan

color7  #cccccc
color15 #ffffff

confirm_os_window_close 0

editor nvim


kitty_mod ctrl+shift
map kitty_mod+b   scroll_page_up
map kitty_mod+f   scroll_page_down
map kitty_mod+enter no_op
map kitty_mod+enter new_window_with_cwd
map kitty_mod+j previous_window
map kitty_mod+k next_window
map kitty_mod+up move_window_forward
map kitty_mod+down move_window_backward
map kitty_mod+6 no_op
map kitty_mod+]       no_op
map kitty_mod+]       next_tab
map kitty_mod+[       no_op
map kitty_mod+[       previous_tab
map kitty_mod+right   no_op 
map kitty_mod+right   move_tab_forward
map kitty_mod+left    no_op 
map kitty_mod+left    move_tab_backward
map kitty_mod+t       no_op
map kitty_mod+t       new_tab_with_cwd

map kitty_mod+0 no_op
map kitty_mod+0 goto_layout stack
map kitty_mod+9 no_op
map kitty_mod+9 goto_layout tall:bias=65
map kitty_mod+8 no_op
map kitty_mod+8 goto_layout fat:bias=65

map kitty_mod+equal     change_font_size all +2.0
map kitty_mod+plus      change_font_size all +2.0
map kitty_mod+minus     change_font_size all -2.0
map kitty_mod+backspace change_font_size all 0

map ctrl+space send_text all \x10